### ISSUE TITLE
環境構築(たいしさん) 

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#12]
localhost:3000にアクセスして、「Yeh! You're on Rails!!」が表示されればOK
このissueに、「Yeh! You're on Rails!!」の画面をスクショして添付すること。
M1のMacの場合はローカル環境で構築、それ以外の場合はdockerを用いて環境構築すること。

**Comment by taishi0202** [comment]
Yeh! You're on Rails!!」の画面を確認しました。
![Screen Shot 2021-03-02 at 20 36 04](https://user-images.githubusercontent.com/74192752/109643210-40a89400-7b97-11eb-89b8-24eacc78a4e8.png)

**Comment by yuki-tachi0219** [comment]
早速のご対応ありがとうございます！
一応、
localhost:3000/static_pages/sample
で画面が見れるか確認していただけますでしょうか。

**Comment by taishi0202** [comment]
確認できました！
![Screen Shot 2021-03-02 at 20 46 42](https://user-images.githubusercontent.com/74192752/109644150-75691b00-7b98-11eb-8890-9f0b4e573411.png)

**Comment by yuki-tachi0219** [comment]
本件、完了といたします 🐧
