### ISSUE TITLE
環境構築(井上さん)

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#13]
localhost:3000にアクセスして、「Yeh! You're on Rails!!」が表示されればOK
このissueに、「Yeh! You're on Rails!!」の画面をスクショして添付すること。
M1のMacの場合はローカル環境で構築、それ以外の場合はdockerを用いて環境構築すること。

**Comment by inouekunihiro** [comment]
## 内容
 - localhost:3000 にアクセスし、「Yeh! You're on Rails!!」が表示されていることを確認。

![image](https://user-images.githubusercontent.com/62821605/109915911-043f7a00-7cf6-11eb-8bda-e7cd62fcbcd7.png)

**Comment by yuki-tachi0219** [comment]
いい感じですね！dockerコンテナうまく起動できたみたいでよかったです 😄 
これで完了といたします！
