### ISSUE TITLE
環境構築(西澤さん)

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#14]
localhost:3000にアクセスして、「Yeh! You're on Rails!!」が表示されればOK
このissueに、「Yeh! You're on Rails!!」の画面をスクショして添付すること。
M1のMacの場合はローカル環境で構築、それ以外の場合はdockerを用いて環境構築すること。

**Comment by nishi622** [comment]
環境構築完了しました。
https://gyazo.com/c3be43165887b463d6a0804d806bb447

**Comment by yuki-tachi0219** [comment]
OKです！完了といたします！！
