### ISSUE TITLE
DB構築 Migration Users関連

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#16]
migrationファイルを作って、DB構造を決める
rails db:migrate を実行して、db/schema.rbを作成すること
DB構造は、GoogleドライブのER図を参考にすること
バリデーションは、画面定義書を参考にすること
対象テーブル: User, UserClassification

データ型の読み方はこちら
https://qiita.com/vermilionfog/items/816fa7de1d0213979929#対応表

db/schema.rb のUserに関する部分をスクショして添付すること

**Comment by taishi0202** [comment]
予定時間：１時間半　
を目標に取り組みます。

**Comment by taishi0202** [comment]
お疲れ様です。
Users関連のDB設計を完了しましたので、db/migrate/schema.rbのスクショを添付します。
お手数おかけいたしますが、ご確認をお願いいたします。
![Screen Shot 2021-03-05 at 16 39 37](https://user-images.githubusercontent.com/74192752/110083125-a84a2380-7dd1-11eb-9a12-7d05df5545ff.png)

**Comment by yuki-tachi0219** [comment]
いい感じです！ここまでの変更をプルリクとして提出していただけますでしょうか。

**Comment by taishi0202** [comment]
DB設計とその修正：3時間
途中で環境構築の再編：6時間30分
合計：9時間30分
