### ISSUE TITLE
DB構築 Migration Products関連

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#17]
migrationファイルを作って、DB構造を決める
rails db:migrate を実行して、db/schema.rbを作成すること
DB構造は、GoogleドライブのER図を参考にすること
対象はProducts関連の合計5テーブル。

データ型の読み方はこちら
https://qiita.com/vermilionfog/items/816fa7de1d0213979929#対応表

db/schema.rb のProductに関する部分をスクショして添付すること

**Comment by inouekunihiro** [comment]
予想完了時間は 3時間としたいと思います！

**Comment by inouekunihiro** [comment]
## 内容
- db/schema.rb のProductに関する部分のスクショを添付させて頂きます。

![image](https://user-images.githubusercontent.com/62821605/110094642-63c58480-7ddf-11eb-9c5e-c5f96a570693.png)

**Comment by yuki-tachi0219** [comment]
良さげなので、この内容をプルリクエストにして提出していただけますでしょうか。
