### ISSUE TITLE
DB構築 Migration Orders関連

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#18]
migrationファイルを作って、DB構造を決める
rails db:migrate を実行して、db/schema.rbを作成すること
DB構造は、GoogleドライブのER図を参考にすること
バリデーションは、画面定義書を参考にすること
対象はOrders関連の合計3テーブル。

データ型の読み方はこちら
https://qiita.com/vermilionfog/items/816fa7de1d0213979929#対応表

db/schema.rb のOrderに関する部分をスクショして添付すること

**Comment by nishi622** [comment]
予想完了時間　３時間

**Comment by nishi622** [comment]
![Uploading image.png…]()

![image](https://user-images.githubusercontent.com/69430659/111164205-2fbd4100-85e1-11eb-8e46-cc164756005f.png)

**Comment by yuki-tachi0219** [comment]
スクショ部分は問題なさそうです 👍
