### ISSUE TITLE
Validation Users関連

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#24]
画面定義書に記載されているバリデーション項目に従って、Validationを定義する。

**Comment by taishi0202** [comment]
予想作業時間：1時間30分
を目標に取り組みます！

**Comment by taishi0202** [comment]
validationの定義：１時間３０分
delete_flagの初期値設定：30分
コンフリクト解消：30分
計：2時間30分
