### ISSUE TITLE
データ投入 Seed Products関連

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#28]
db/seeds.rb にProduct関係の仮データを入れること

コンソール上で
rails db:seed
を実行して、rails console上でデータが正しく作られたかどうか確認する。

rails console上で Product.all を実行 → Product一覧が出てくる。これをスクショして添付すること

**Comment by inouekunihiro** [comment]
予想完了時間は、3時間です！

**Comment by inouekunihiro** [comment]
- お疲れ様です！ Product.all の取得したデータ一覧のスクショです！
<img width="851" alt="スクリーンショット 2021-03-18 0 12 37" src="https://user-images.githubusercontent.com/62821605/111491426-32559d00-877f-11eb-9284-d8e8fd779c09.png">

**Comment by yuki-tachi0219** [comment]
いい感じですね 👍 
このままプルリクエストをお願いします 🐧
