### ISSUE TITLE
データ投入 Seed Orders関連

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#29]
db/seeds.rb にOrders関係の仮データを入れること
...

コンソール上で
rails db:seed
を実行して、rails console上でデータが正しく作られたかどうか確認する。

rails console上で Order.all を実行 → Order一覧が出てくる。これをスクショして添付すること

**Comment by nishi622** [comment]
予想時間３時間

**Comment by nishi622** [comment]
![image](https://user-images.githubusercontent.com/69430659/112178297-fcac2a80-8c3c-11eb-9ab1-b24f35e05c66.png)

**Comment by yuki-tachi0219** [comment]
id が2 のOrderDetailについてですが、order_idは2だと思います。
それ以外は問題なさそうなので、修正できたらプルリクをお願いします。

**Comment by nishi622** [comment]
修正します。

**Comment by nishi622** [comment]
修正しました
![image](https://user-images.githubusercontent.com/69430659/112306974-bfe73e80-8ce3-11eb-9d77-20bbc7b5c4d2.png)

**Comment by nishi622** [comment]
実際の作業時間　４時間30分
