### ISSUE TITLE
ユーザー情報画面

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#31]
path: /users/:id
controller#action: Users#show
参考モックアップ: user_info.html

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by taishi0202** [comment]
予想完了時間：2時間
でお願いします！

**Comment by taishi0202** [comment]
お疲れ様です。
モックアップ作成しました。スクショを貼ります。
![Screen Shot 2021-03-16 at 21 34 19](https://user-images.githubusercontent.com/74192752/111309678-86895000-869f-11eb-8ab1-474f6f8dba81.png)

**Comment by yuki-tachi0219** [comment]
ありがとうございます！
この画面は、
`localhost:3000/users/1`というURLならidが1のユーザーの情報、`localhost:3000/users/2`というURLならidが2のユーザーの情報を取得してここに表示したいんですよね。
以下の記事が参考になるかと思います。
https://railstutorial.jp/chapters/sign_up?version=5.1#sec-showing_users

**Comment by taishi0202** [comment]
モックアップのスクショを添付します。
localhost:3000/users/2で出してます。
![Screen Shot 2021-03-17 at 23 35 58](https://user-images.githubusercontent.com/74192752/111485159-b9077b80-8779-11eb-8ea1-c4404489f644.png)

**Comment by taishi0202** [comment]
ユーザーIDのところ表示させました！
![Screen Shot 2021-03-18 at 0 02 51](https://user-images.githubusercontent.com/74192752/111489231-4b5d4e80-877d-11eb-80a7-bfc34cb073d0.png)

**Comment by yuki-tachi0219** [comment]
last_nameとfirst_nameの順番を入れ替えた上でプルリクエストをお願いいたします 🐧

**Comment by taishi0202** [comment]
実質対応時間：2時間
