### ISSUE TITLE
商品詳細画面

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#49]
path: /products/:id
controller#action: Products#show
参考モックアップ: product_details.html, product_details2.html

URLで指定したidを持つ商品がある場合は、その商品の情報を表示(product_details.html)
商品が存在しない場合は、「該当商品が見つかりませんでした」と表示(product_details2.html)

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by inouekunihiro** [comment]
予想完了時間は4時間です！

**Comment by yuki-tachi0219** [comment]
- [ ] ルーティング
- [ ] Controller作成 (ProductsController)
- [ ] アクション作成 (showアクション)
  - Users#showを参考にする
- [ ] 商品があるときの画面実装
- [ ] 商品が見つからないときの画面実装 
- [ ] 部分テンプレートに書いてあるhtmlを除く
- [ ] 動作確認

**Comment by inouekunihiro** [comment]
- 少し表示にズレがあるのですが、表示を分岐させることができました！
<img width="1440" alt="スクリーンショット 2021-03-30 18 23 01" src="https://user-images.githubusercontent.com/62821605/112974014-eba77000-918c-11eb-9f96-9b4e75490009.png">

<img width="1440" alt="スクリーンショット 2021-03-30 18 23 34" src="https://user-images.githubusercontent.com/62821605/112974006-e9451600-918c-11eb-991d-29bd69b5631e.png">

**Comment by yuki-tachi0219** [comment]
いい感じですね！
このままプルリクお願いします。
レイアウト崩れについては、たいしさんのプルリクでも話してましたがbootstrapバージョン違いの問題と思われます。
