### ISSUE TITLE
注文詳細画面

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#51]
path: /orders/:id
controller#action: Orders#show
参考モックアップ: order_details.html, order_details2.html

URLで指定したidを持つ注文がある場合は、その注文の情報を表示(order_details.html)
注文が存在しない場合は、「該当の注文は見つかりませんでした」と表示(order_details2.html)

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by nishi622** [comment]
作業予想時間　8時間
作業期日　4月6日（火）まで

**Comment by nishi622** [comment]
- [ ] ルーティングの記述
- [ ] 検索した結果を表示する
- [ ] 検索結果がない時のページ表示
- [ ] 注文履歴に戻るボタン
- [ ] 注文状態：準備中　の商品がある時のみ注文キャンセルボタンを表示する
- [ ] 商品の金額を合計して表示する機能

**Comment by nishi622** [comment]
![image](https://user-images.githubusercontent.com/69430659/114041474-8ad01400-98bf-11eb-9c22-efbddda9e2f1.png)

![image](https://user-images.githubusercontent.com/69430659/114041559-9d4a4d80-98bf-11eb-814f-79af4db38d6e.png)

**Comment by yuki-tachi0219** [comment]
idが存在するときの画面ができてるみたいなので、プルリク出してもいいですよ。
idがない場合の画面のエラーをそこで確認することもできます。

**Comment by nishi622** [comment]
![image](https://user-images.githubusercontent.com/69430659/114183488-b5cd6d00-997e-11eb-89c6-33c038441630.png)

**Comment by nishi622** [comment]
またまとめてコミットしてしまいました。すいません。
