### ISSUE TITLE
ユーザー情報修正画面

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#52]
path: /users/:id/edit
controller#action: Users#edit
参考モックアップ: user_information_correction.html

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。
「修正」「退会」ボタンを押した後の機能は実装不要

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by taishi0202** [comment]
- [ ] editアクションを作る
       ・修正と退会へ飛ぶ機能のの作成？（updateとdeleteへの橋渡し的な？)
- [ ] routes.rbにget 'users/edit'を追加
- [ ] edit.html.erbを作る
       ・show.html.erbの書き方がパクれそう
       ・モックアップからコピペ
- [ ] 動作確認
- [ ] スクショを貼る

予想実装時間４時間
納期：3/27　土曜日

**Comment by yuki-tachi0219** [comment]
> 修正と退会へ飛ぶ機能のの作成？（updateとdeleteへの橋渡し的な？)

これはコントローラ内には書かないですね。edit.html.erb内に書くことになります。update, deleteアクションに飛ぶようなリンクを貼ります。このチケットではリンクまでは作らなくていいですよ。

> routes.rbにget 'users/edit'を追加

`resources :users` やってるので不要だと思います

> edit.html.erbを作る

ある程度はパクれると思いますが、form_for というメソッドを新たに使うことになります。ググって公式ドキュメントを見たりRailsTutorialを見たりしながらやってみてください。

**Comment by taishi0202** [comment]
実働時間
ユーザー情報修正画面の作成：4時間
