### ISSUE TITLE
ユーザー情報更新

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#57]
アクション：Users#update
更新処理に成功したら ユーザー情報画面へ遷移、更新処理に失敗したら情報修正画面に戻り、エラーメッセージを表示させること

**Comment by yuki-tachi0219** [comment]
参考
https://pikawaka.com/rails/update
https://railstutorial.jp/chapters/updating_and_deleting_users?version=5.1#sec-updating_users

**Comment by taishi0202** [comment]
- [ ] updateアクションを作る
- [ ] strong parameterを作る
- [ ] 動作確認
- [ ] プルリク出す
予想時間　３時間
納期 3/29目標！

**Comment by yuki-tachi0219** [comment]
チェックリストに書かなくてもいいですが、updateアクションの中には
 - idに対応するユーザーの情報取得
 - 情報更新
 - リダイレクト
 があることをイメージしながら進めてみてください

**Comment by taishi0202** [comment]
実動時間
ユーザー情報画面の作成：２時間
VScodeの初期設定：１時間
