### ISSUE TITLE
エラーメッセージの日本語化

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#59]
参考：https://qiita.com/Ushinji/items/242bfba84df7a5a67d5b

**Comment by taishi0202** [comment]
- [ ] gemのinstall
- [ ] application.rbにコードを書き込む
- [ ] locales/models/ja.ymlを作成
- [ ] application.rbに読みこます。
予想時間：２時間
納期：3/30
よろしくお願いします！

**Comment by yuki-tachi0219** [comment]
>納期：3/30

早すぎワロタ

**Comment by taishi0202** [comment]
タッティーさんのこと全然考えてない納期でした・・・🙇‍♂️

**Comment by yuki-tachi0219** [comment]
簡単なタスクなので目標納期そのままでも大丈夫ですよー
