### ISSUE TITLE
ログイン画面

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#61]
path: /login
controller#action: Sessions#new
参考モックアップ: login.html

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

画面が表示できたら、スクショを貼り付けること。
ログイン処理(ログインボタンを押したあとの処理)は実装不要

参考：https://qiita.com/d0ne1s/items/7c4d2be3f53e34a9dec7

**Comment by taishi0202** [comment]
- [ ] Session_controllerの作成
・newメソッドの作成（create、destroyも必要？）
・createメソッドでログインできる場合とできない場合の条件分岐を作成
（できない場合は、再びログイン画面へ？）
- [ ] routes.rbに対応のpathを追加
- [ ] new.html.erbを作成
・モックアップを参考に修正。
・edit.html.erbを参考にform_forを使う
- [ ]  動作確認
- [ ] スクショはる
- [ ] プルリクを出す
予想時間５時間
納期4/2
よろしくお願いします！！

**Comment by taishi0202** [comment]
実動時間
ログイン画面の作成：１時間
