### ISSUE TITLE
ログイン、ログアウト処理

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#63]
ログイン: POST /login
ログアウト: DELETE /logout
ログイン後のリダイレクト先はユーザー詳細ページ
ログアウト後のリダイレクトはログインページ

ヘッダーにログアウトリンクを付けること

ログイン、ログアウト処理はHelperで定義すること。メソッド名はそれぞれlogin(user), logout

**Comment by taishi0202** [comment]
- [ ] createメソッドの作成
・ユーザーの検索と認証
　find_byメソッドとauthenticateメソッドを使う
　if条件分岐で、find_byメソッドでuser.idが見つかり且つログインに成功したとき、ユーザー詳細画面へ
　ユーザーが見つからない、またはログインに失敗したとき、ログイン画面へ
　ログインに失敗したときのエラーメッセージを表記。
（Session_controllerはActivrrecordではないのでuserとは別手法？)
- [ ] sessions_helper.rbの作成
・login(user)メソッドとlogoutメソッドの実装
- [ ] application_controller.rbにsessions_helperを読み込ませる
（クラスの継承により確かこれで大丈夫なはず・・・曖昧）
- [ ] 部分テンプレートheaderにリンク付けをする

予想時間　６時間
納期4/2

よろしくお願いします！
