### ISSUE TITLE
商品検索画面(検索ロジック以外)

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#65]
path: /products
controller#action: Products#index
参考モックアップ: after_item_search.html

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

検索機能は除き、最初から全商品が表示されている状態にすること。
ページネーション機能は、kaminari gemを使うこと。
参考：https://qiita.com/d_nagano1002/items/fd90340c50324e845fe1

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by inouekunihiro** [comment]
- とりあえず、モックアップの画面を表示させることができたのですが、次は Product モデルの全商品を表示させるようにした方がよろしいでしょうか？

![スクリーンショット 2021-04-02 19 55 03](https://user-images.githubusercontent.com/62821605/113409999-5eaf2180-93ed-11eb-8710-cbec6ff5b618.png)

**Comment by yuki-tachi0219** [comment]
そうですねー
Productを15個くらい作って、ページネーションもちゃんと動くか試してみましょうか。

**Comment by inouekunihiro** [comment]
- seeds.rb にデータを入れて Product データを多数作りました。すると、下のようなページネーションが出てきてクリックすると動いていました！
![スクリーンショット 2021-04-02 21 42 41](https://user-images.githubusercontent.com/62821605/113416475-6629f700-93fc-11eb-8f95-b50b224e17be.png)

**Comment by yuki-tachi0219** [comment]
見た目（CSS）が反映されてないですね 🤔 
とりあえずプルリク出していただきましょうか
