### ISSUE TITLE
認可処理機能

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-violet#68]
ログインしていない場合、users#show, editページを見れないようにして自動的にログインページに遷移するよう、sessions_helper.rbに実装すること。
メソッド名はlogged_in_user
フラッシュメッセージは「ログインしてください。」

ログインしていたとしても、他人に関係するページは見れないようにして、自動的にroot_pathに遷移するよう、sessions_helper.rb に実装。
メソッド名はcorrect_user
フラッシュメッセージは「他人の情報にアクセスすることはできません。」

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by taishi0202** [comment]
- [ ] logged_in_userメソッドをsessions_helper.rbに追加
- [ ] correct_userメソッドをsessions_helper.rbに追加
- [ ] Include SessionsHelperをSessions _controllerからapplication_controllerへ移動
- [ ] users_controllerでbefore_actionを定義
- [ ] 動作確認
- [ ] スクショ貼る

予想時間　３時間
納期4/9
よろしくお願いします！

**Comment by taishi0202** [comment]
各認可機能のスクショを貼ります！
![Screen Shot 2021-04-08 at 21 03 31 (2)](https://user-images.githubusercontent.com/74192752/114023958-72a3c900-98ae-11eb-9286-3bcca14f3650.png)
![Screen Shot 2021-04-08 at 21 03 09 (2)](https://user-images.githubusercontent.com/74192752/114023979-78011380-98ae-11eb-8b64-014a4346395b.png)

**Comment by yuki-tachi0219** [comment]
問題なさそうなので、このままプルリクやったりましょー＼(^o^)／

**Comment by taishi0202** [comment]
実質対応時間　３時間
認可機能処理の実装：３時間
