### ISSUE TITLE
TOPページ画面

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#72]
path: /
controller#action: StaticPages#home
参考モックアップ: index.html, indes_login.html

ログインしているときとしていないときで表示画面を切り替えること。
リンク先が存在するものについては、リンクを設定すること。

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by taishi0202** [comment]
- [ ] 参考モックアップをコピペ
- [ ] view/products/show.html.erbを参考に条件分岐
- [ ] リンク先の指定
- [ ] 動作確認
- [ ] スクショ
予想時間：２時間
納期4/12
よろしくお願いします！

**Comment by taishi0202** [comment]
お疲れ様です。
スクショ貼ります！
![Screen Shot 2021-04-11 at 19 07 16 (2)](https://user-images.githubusercontent.com/74192752/114300028-36b07400-9af9-11eb-9938-56df7cad98b2.png)
![Screen Shot 2021-04-11 at 19 08 35 (2)](https://user-images.githubusercontent.com/74192752/114300044-55af0600-9af9-11eb-9e16-482d21804323.png)

**Comment by yuki-tachi0219** [comment]
プルリクGOで！

**Comment by taishi0202** [comment]
実質対応時間
TOPページ作成：３時間
