### ISSUE TITLE
ユーザー登録ページ、登録処理

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#73]
登録ページ
path: GET /signup
controller#action: Users#new
参考モックアップ: sign_up.html

登録処理
path: POST /signup
controller#action: Users#create

登録後のリダイレクト先については画面定義書参照
登録に成功したら「ユーザーを登録しました。こちらからログインしてください。」というフラッシュメッセージを出すこと
登録に失敗したら、問題箇所を指摘するメッセージを表示すること。ユーザー修正画面と同様に実装すればOK

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

**Comment by inouekunihiro** [comment]
予想完了時間：4時間

作業内容：
- [ ] Users コントローラーに new アクションを追加
- [ ] Users コントローラーに create アクションを追加
- [ ] sign_up.html.erb を作成
- [ ] 登録に成功した場合の画面遷移とフラッシュメッセージの表示
- [ ] 登録に失敗した場合の画面遷移とメッセージの表示

納期：4/12(月)

**Comment by yuki-tachi0219** [comment]
>sign_up.html.erb を作成

これはnew.html.erbですね

**Comment by inouekunihiro** [comment]
あっ、なるほどですね！

path: GET /signup

となっていたため勘違いしていました！

**Comment by inouekunihiro** [comment]
お疲れ様です！

一つ質問なのですが、一通りユーザー登録ページのフォームを作成することができ、
バリデーションに引っかからないような文言を入力して「登録」ボタンを押してみました。

エラーメッセージはうまく表示させることができたのですが、
その下に「User classificationを入力してください」と言ったエラーがあり、
ユーザーの分類？のようなものを入力して欲しいと言ったものが返ってきました。

これは何かしらの入力フォームが足りないということでしょうか？
確認してみましたが、入力すべきフォームは全て作成していました。

画像（1/2）
![スクリーンショット 2021-04-14 10 12 24](https://user-images.githubusercontent.com/62821605/114640000-29b69f00-9d0a-11eb-9e37-cce0c2515dc8.png)

画像（2/2）
![スクリーンショット 2021-04-14 10 12 43](https://user-images.githubusercontent.com/62821605/114639986-24595480-9d0a-11eb-8058-3b469f53cd39.png)


ちなみに、「ログインはこちらから」のボタンを押した後は、
"/login" のページに遷移されるようにしました。

お手数お掛けしますが、
よろしくお願いします🙏

**Comment by yuki-tachi0219** [comment]
user classification忘れてましたね。
userの親にUserClassificationモデルがついているのですが、それを指定しないといけないですね。
ユーザー作成時、自動的にid: 1 のUserClassificationがつくようにしていただければと思います。
