### ISSUE TITLE
商品検索画面(検索ロジック)

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#77]
参考：https://qiita.com/yusuko/items/cff4e46aeafbc3beecf2
商品の商品名カラムに対して部分一致の検索をかけること。
検索キーワードがないときは、全商品を表示させること。

**Comment by inouekunihiro** [comment]
予想完了時間：8時間

作業内容：
- products_controller.rb に商品検索ロジック部分を追記
- products/index.html.erb に検索に関するコードを記述
- product.rb に検索に関するコードを記述
- 動作確認（商品名の部分一致検索をかける）
- 動作確認（検索したものがない場合は、全商品が表示されているか）

納期：4/25（日）
