### ISSUE TITLE
ユーザー退会

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#79]
path: DELETE /users/:id
controller#action: users#destroy
退会をボタンを押したら、
「ユーザーデータが全て削除されます。本当に退会しますか？」
というダイアログボックスが開くようにすること

退会後、トップページに遷移すること
自動的にログアウト状態になっているか確認すること

**Comment by taishi0202** [comment]
- [ ] users.controllerにdestroyメソッドをつくる
・ユーザーのidを特定する
・そのユーザーをdestroyする
・redirect_to root_urlの追加
・flash[:success] = "退会しました”の追加
- [ ] ユーザー修正画面に退会のリンクを作る
・ダイログボックスを追加する
- [ ] 動作確認
- [ ] プルリク出す
予想時間２時間
納期4/12

よろしくお願いします！

**Comment by yuki-tachi0219** [comment]
はっや
