### ISSUE TITLE
カート機能

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-violet#81]
カートページ
path: POST carts/add_cart
controller#action: carts#show,
参考モックアップ: cart_list.html

削除処理
path: DELETE carts/destroy
controller#action: Users#create

カートへ商品を追加、削除する機能を実装。

注文確定のボタン押下後、注文情報をDBへ格納し、購入画面へ遷移

sessionを使用した実装にすること。

**Comment by nishi622** [comment]
- [ ] カートに情報を追加（product_id, category_name, price)
- [ ] カート内の金額を合計
- [ ] カート画面で個数を変更
- [ ] 

- [ ] カート内商品一覧画面作成
- [ ] カートに商品がない場合の画面

- [ ] 購入機能
- [ ] 購入後はカートを空に

**Comment by nishi622** [comment]
予想時間２５時間

期日4月22日

**Comment by yuki-tachi0219** [comment]
購入完了画面を表示させるのもお願いします 🙏
