### ISSUE TITLE
注文履歴

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#82]
path: /orders
controller#action: Orders#index
参考モックアップ: order_history.html, order_history_no_exit.html

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。
「直近3か月の注文を表示｣ボタンは実装しない
注文が存在しない場合の画面も、画面定義書参照のこと。

ページネーション機能は、kaminari gemを使うこと。

**Comment by taishi0202** [comment]
- [ ] indexメソッドを作成
- `@order = Order.allだけ？
- [ ] 対応するindex.hml.erbを作成
- [ ] モックアップを参考にhtml.erbの修正
- [ ] 修正したhtml.erbをkaminariに合わせてコード修正
- <%= paginate @orders %>だけ？
- [ ] 動作確認
- [ ] プルリクへ
予想時間　６時間
納期 4/15

よろしくお願いします！

**Comment by yuki-tachi0219** [comment]
Products#index を見ていただければ、controllerに何を書けばいいかイメージできるかと思います 👍

**Comment by taishi0202** [comment]
お疲れ様です！
すみません・・・納期明日中に伸ばします！

よろしくお願いします！

**Comment by taishi0202** [comment]
実質作業時間
13時間
